name: Mobile Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android APK
        uses: Ayowel/renpy-setup-action@v2
        with:
          sdk-version: '8.2.1'
          action: 'android_build'
          project-path: '.'
          # 强制指定输出目录
          output-dir: 'dist'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: 'dist/*.apk'
