name: Mobile Build APK
on: 
  workflow_dispatch: # 允许手动点击按钮触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Ren'Py Android
        uses: Ayowel/renpy-setup-action@v2
        with:
          sdk-version: '8.2.1'
          # 这里会自动处理安卓构建
          action: 'android_build'
          # 你的项目路径，如果是根目录就写 .
          project-path: '.'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-game-apk
          path: '**/*.apk'
